In [8]:
print(list(range(0,100,5)))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [1]:

months = ["Jan", "Feb", "Mar"]
for month in months:
    print(month)

Jan
Feb
Mar


In [3]:
for num in range(0,10):
    print(num)

0
1
2
3
4
5
6
7
8
9


In [4]:
names = ["thom", "john", "peter"]
for index in range(len(names)):
    names[index] = names[index].title()
print(names)

['Thom', 'John', 'Peter']


In [10]:
movies = {'Titanic': 1997, 'Finding Nemo': 2003}
for (key, value) in movies.items():
    print('The movie {} was made in {}'.format(key, value))

The movie Titanic was made in 1997
The movie Finding Nemo was made in 2003


In [12]:
numbers = [1, 2, 3, 4, 5]
print(list(filter(lambda number: number % 2 ==0, numbers)))

[2, 4]


In [14]:
list_2 = list(range(1, 4))
list_3 = list(range(1, 4))
list_sum = []
for index in range(3):
    list_2[index] = list_2[index] ** 2
    list_3[index] = list_3[index] ** 3
    list_sum.append(list_2[index] + list_3[index])
print(list_sum)

[2, 12, 36]


In [16]:
import numpy as np
array_2 = np.arange(1, 4) ** 2
array_3 = np.arange(1, 4) ** 3
print(array_2 + array_3)

[ 2 12 36]


In [17]:
print(np.power(np.array([1,2,3]), 4))

[ 1 16 81]


In [18]:
print(np.negative(np.array([1,2,3])))

[-1 -2 -3]


In [20]:
x = np.arange(4)
y = np.arange(4)
z = np.arange(4)

multi = np.array([x,y,z])
print(multi)
print(multi.shape)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
(3, 4)


In [25]:
w = np.linspace(1, 10, 10)
print(w)
print(w.shape)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(10,)


In [33]:
w = np.arange(12).reshape(4,3)
i = np.arange(12).reshape(2,3,2)
print(w)
print(i)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [44]:
i[1,1,1]
print(i[1, :2, :2])
print(i[1, :, :])
print(i[1, ...])
print(i[:, 0, 0])

[[6 7]
 [8 9]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[0 6]


In [47]:
print(i[i > 5])

[ 6  7  8  9 10 11]


In [49]:
i.max()

11

In [51]:
print(w)
print(w.ravel())//points to a same array, will change value of the original array
print(w.flatten()) // copy of the original array, wont change value of original array

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [52]:
ravel = w.ravel()
ravel[2] = 100
print(ravel)
print(w)

[  0   1 100   3   4   5   6   7   8   9  10  11]
[[  0   1 100]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [53]:
flatten = w.flatten()
flatten[2] = 99
print(flatten)
print(w)

[ 0  1 99  3  4  5  6  7  8  9 10 11]
[[  0   1 100]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [56]:
#transpose
y = np.arange(9)
y.shape = [3, 3]
print(y)
print(y.transpose())
print(y.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [57]:
#resize
print(np.resize(y, (6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [65]:
#zeros, ones and eye, randomw
print(np.zeros((2,3), dtype=int))
print(np.ones((2,3), dtype=int))
print(np.eye((3), dtype=int))
print(np.random.rand(3,3))

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0.99683549 0.07907195 0.11599112]
 [0.83805808 0.95096133 0.56424412]
 [0.05017809 0.54865331 0.27167506]]


In [68]:
#matrix multiplication
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2,3)
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3,2)
print(mat_a * mat_b)
print(np.matmul(mat_a, mat_b))
print(mat_a @ mat_b)

[[ 29 -16]
 [ 38   6]]
[[ 29 -16]
 [ 38   6]]
[[ 29 -16]
 [ 38   6]]


In [69]:
# Stacking
a = np.arange(4).reshape(2,2)
print(a)

[[0 1]
 [2 3]]


In [74]:
b = np.arange(4,10).reshape(2,3)
c = np.arange(4,10).reshape(3,2)
print(np.hstack((a,b)))
print(np.vstack((a,c)))

[[0 1 4 5 6]
 [2 3 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [80]:
#concatenate (can achive both veritcal and horizontal stackings)
print(np.concatenate((a, b), axis = 1))
print(np.concatenate((a, c), axis = 0))
print(np.hstack((a,b)) == np.concatenate((a, b), axis = 1))

[[0 1 4 5 6]
 [2 3 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [83]:
#depth stacking
d = a * 2
print(d)

[[0 2]
 [4 6]]


In [85]:
depth_stack = np.dstack((a, d))
print(depth_stack)
print(depth_stack.shape)

[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]
(2, 2, 2)


In [86]:
# column_stack is the same hstack when array is not 1D array
print(np.column_stack((a, d)) == np.hstack((a, d)))

[[ True  True  True  True]
 [ True  True  True  True]]


In [87]:
# column_stack defers from hstack when array is 1D array
x = np.arange(4)
y = x * 2
print(np.column_stack((x, y)))
print(np.hstack((x,y)))

[[0 0]
 [1 2]
 [2 4]
 [3 6]]
[0 1 2 3 0 2 4 6]
